- name: Pg repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

- name: Pg repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc validate_certs=no

- name: Install
  apt: name={{ item }} update_cache=yes
  with_items:
    - postgresql-9.4
    - postgresql-contrib-9.4
    - postgresql-server-dev-9.4

- name: Listen on all interfaces
  replace: dest=/etc/postgresql/9.4/main/postgresql.conf regexp='^#listen.*$' replace="listen_addresses = '*'"
  register: pg_settings

- name: Define hba rules
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf
  register: pg_settings

- name: Restart postgresql
  service: name=postgresql state=restarted
  when: pg_settings.changed

- name: Create db user
  postgresql_user: name=ubuntu password=httgtyrehey role_attr_flags=CREATEDB,NOSUPERUSER
  sudo_user: postgres

- name: Create db
  postgresql_db: name=usweather owner=ubuntu encoding='UTF-8' template='template0'
  sudo_user: postgres